import setting from "../../../../setting.json"

describe('First step', function(){
  // it('Restore data', function(){
  //   cy.request('https://drug.s2corp.vn/api/restoreDB/DB_API')
  //   cy.wait(1000)
  // })
  it('Visit webside smartpharmacy', function(){
    cy.visit('https://smartpharmacy.digihcs.com/')
  })
  it('Finds an elements', function(){
    cy.get('input[type=text]')
    .type('admin').should('have.value', 'admin')

    cy.get('input[type=password]')
    .type('12345678').should('have.value', '12345678')

    cy.get('input[type=checkbox]').check()

    cy.get('.bt-dang-nhap').click()
    cy.get('.notification-message').contains('Đăng nhập thành công!');
    // cy.visit('https://smartpharmacy.digihcs.com/retail')
    // nhập kho
    cy.visit(setting.webLink + setting.storeImport)
    // cy.contains('Quản lý').click({force: true})
    // cy.contains('Nhập kho').click({force: true})
    cy.wait(setting.waitdata)
    cy.get('input[name="storeImportForm.selectStore"]').type('Shop', {force: true})
    cy.wait(setting.wait)
    cy.get('.Select-menu').first().click()
    cy.wait(setting.wait)
    cy.get('button[name="createStockModel.create"]').click()
    cy.wait(setting.wait)
    cy.get('input[name="storeImportForm.billCode"]').type('T2-1X')
    cy.wait(setting.wait)
    cy.get('input[name="storeImportForm.selectProvider"]').type('Nhà cung cấp', {force: true})
    cy.wait(setting.wait)
    cy.get('.Select-menu').first().click()
    cy.wait(setting.wait)
    cy.get('button[name="addNewDialog.save"]').click()
    cy.wait(setting.wait)
    cy.get('input[name="searchTool.selectStock"]').type('1', {force: true})
    cy.wait(setting.waitdata)
    cy.get('.Select-menu').first().click()
    cy.wait(setting.wait)
    cy.get('input[name="quantity"]').type('50')
    cy.get('button[name="stockImportDetail.add"]').click({force: true})
    cy.wait(setting.wait)
    cy.get('button[name="importFormMenu.verify"]').click({force: true})
    cy.wait(setting.waitdata)
    cy.get('button[name="storeImportForm.verify"]').click()

    cy.wait(setting.waitdata)
    cy.contains('Bán hàng').click({force: true})
    cy.wait(setting.wait)
    cy.get('a[name=select-shop]').click({force: true})
    cy.wait(setting.wait)
    cy.get('li[name=list-shop-0]').click({force: true})
    cy.wait(setting.wait)
    cy.get('li[name=btn-create-cart]').click({force: true})

    // Select medicine
    cy.wait(setting.wait)
    cy.get('input[name=select-stock]').type('1000', {force: true})
    cy.wait(setting.waitdata)
    cy.get('.Select-menu').first().click()
    cy.wait(setting.waitdata)
    cy.get('input[name=input-quantity-0]').type('5')
    cy.wait(setting.wait)
    cy.get('button[name=btn-add-stock]').click({force: true})
    // cy.contains('Thêm thành công sản phẩm 100000')
    cy.wait(setting.wait)
    cy.get('button[name="btn-edit-stock-sell-0"]').click({force: true})
    cy.wait(setting.waitdata)
    cy.get('input[name="input-edit-sell-quantity-0-0"]').type('6')
    cy.wait(setting.waitdata)
    cy.get('button[name=btn-save-sell-quantity-0]').click()
    cy.wait(setting.wait)
    cy.contains('Thay đổi số lượng thành công')

    cy.wait(setting.wait)
    cy.get('button[name=btn-edit-stock-sell-0]').click()
    cy.wait(setting.wait)
    cy.get('select[name=select-discount-stock-0]').select('($)', {force: true})
    cy.wait(setting.wait)
    cy.get('input[name=input-discount-stock-0]').type('15000')
    cy.wait(setting.wait)
    cy.get('button[name=btn-save-discount-stock-0]').click()
    //cy.contains('Khuyến mãi thành công cho sản phẩm 100000')
    cy.wait(setting.wait)
    cy.get('button[name=btn-detail-stock-0]').click()
    cy.wait(setting.wait)
    cy.get('button[name=btn-close-stock-info]').click()

    cy.wait(setting.wait)
    cy.get('input[name=select-stock]').type('a', {force: true})
    cy.wait(setting.wait)
    cy.get('.Select-menu').first().click()
    cy.wait(setting.wait)
    cy.get('input[name=input-quantity-0]').type('53')
    cy.wait(setting.wait)
    cy.get('button[name=btn-add-stock]').click()
    // cy.contains('Không đủ hàng trong kho')
    cy.wait(setting.wait)
    cy.get('button[name=btn-delete-stock-sell-0]').click({force: true})
    //lưu đơn thuốc
    cy.wait(setting.wait)
    cy.get('button[name=btn-prescription-saved]').click()
    cy.wait(setting.wait)
    cy.get('button[name=btn-close-list-prescription]').click()
    cy.wait(setting.wait)
    cy.get('button[name=btn-history-cart]').click()
    cy.wait(setting.wait)
    cy.get('button[name=btn-close-cart-history]').click()
    cy.wait(setting.wait)
    cy.get('button[name=btn-note]').click()
    cy.wait(setting.wait)
    cy.get('textarea[name=input-cart-note]').type('abc')
    cy.wait(setting.wait)
    cy.get('button[name=btn-confirm-save-cart-note]').click()


    //xóa đơn hàng đã lưu trước chưa thanh toán
    cy.wait(setting.wait)
    cy.get('li[name=list-doc-0]').click({force: true})
    cy.wait(setting.wait)
    cy.get('button[name=btn-cancel-cart]').click()
    cy.wait(setting.wait)
    cy.get('textarea[name=input-reason-cancel-cart]').type('a')
    cy.wait(setting.wait)
    cy.get('button[name=btn-confirm-delete-cart]').click()



  })
})
